from enum import Enum
from BaseClasses import Location
from typing import Dict, NamedTuple, Optional

class CCLocation(Location):
    game = "Cookie Clicker"

class CCAchievement:
    OFFSET = 42069000 + 1 # TODO remove +1 offset to prevent errors

    def __init__(self, id, name, building, sphere):
        self.id = self.OFFSET + id
        self.name = name
        self.building = BUILDING(building).value
        self.sphere = SPHERE(sphere).value

class SPHERE(Enum):
    EXCLUDED = -1

    # Game progression spheres
    ZERO = 0
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4
    FIVE = 5
    LATEGAME = 6

    # Special sphere
    ENDGAME = 10 # A bit different from progression because we need specifically everything
    GRANDMA = 66

class BUILDING(Enum):
    NOTHING = -1
    CURSOR = 0
    GRANDMA = 1
    FARM = 2
    MINE = 3
    FACTORY = 4
    BANK = 5
    TEMPLE = 6
    WIZARD_TOWER = 7
    SHIPMENT = 8
    ALCHEMY_LAB = 9
    PORTAL = 10
    TIME_MACHINE = 11
    ANTIMATTER_CONDENSER = 12
    PRISM = 13
    CHANCEMAKER = 14
    FRACTAL_ENGINE = 15
    JAVASCRIPT_CONSOLE = 16
    IDLEVERSE = 17
    CORTEX_BAKER = 18
    YOU = 19

achievements = [
    # Total baked
    CCAchievement(0, "Wake and bake", -1, 0),
    CCAchievement(1, "Making some dough", -1, 0),
    CCAchievement(2, "So baked right now", -1, 0),
    CCAchievement(3, "Fledgling bakery", -1, 0),
    CCAchievement(4, "Affluent bakery", -1, 0),
    CCAchievement(5, "World-famous bakery", -1, 0),
    CCAchievement(6, "Cosmic bakery", -1, 1),
    CCAchievement(7, "Galactic bakery", -1, 1),
    CCAchievement(8, "Universal bakery", -1, 2),
    CCAchievement(9, "Timeless bakery", -1, 2),
    CCAchievement(10, "Infinite bakery", -1, 2),
    CCAchievement(11, "Immortal bakery", -1, 2),
    CCAchievement(12, "Don't stop me now", -1, 3),
    CCAchievement(13, "You can stop now", -1, 3),
    CCAchievement(14, "Cookies all the way down", -1, 4),
    CCAchievement(15, "Overdose", -1, 4),
    CCAchievement(223, "How?", -1, 5),
    CCAchievement(224, "The land of milk and cookies", -1, 5),
    CCAchievement(225, "He who controls the cookies controls the universe", -1, 6),
    CCAchievement(226, "Tonight on Hoarders", -1, 6),
    CCAchievement(227, "Are you gonna eat all that?", -1, 6),
    CCAchievement(228, "We're gonna need a bigger bakery", -1, 6),
    CCAchievement(229, "In the mouth of madness", -1, 6),
    CCAchievement(230,
                  "Brought to you by the letter <div style=\"display:inline-block;background:url(img/money.png);width:16px;height:16px;\"></div>",
                  -1, 6),
    CCAchievement(279, "The dreams in which I'm baking are the best I've ever had", -1, 6),
    CCAchievement(280, "Set for life", -1, 6),
    CCAchievement(372, "Panic! at Nabisco", -1, 6),
    CCAchievement(373, "Bursting at the seams", -1, 6),
    CCAchievement(374, "Just about full", -1, 6),
    CCAchievement(375, "Hungry for more", -1, 6),
    CCAchievement(390, "Feed me, Orteil", -1, 6),
    CCAchievement(391, "And then what?", -1, 6),
    CCAchievement(429, "I think it's safe to say you've got it made", -1, 6),
    CCAchievement(451, "A sometimes food", -1, 6),
    CCAchievement(452, "Not enough of a good thing", -1, 6),
    CCAchievement(453, "Horn of plenty", -1, 6),
    CCAchievement(470, "Large and in charge", -1, 6),
    CCAchievement(471, "Absolutely stuffed", -1, 6),
    CCAchievement(472, "It's only wafer-thin", -1, 6),
    CCAchievement(534, "Think big", -1, 6),
    CCAchievement(535, "Hypersize me", -1, 6),
    CCAchievement(536, "Max capacity", -1, 6),
    CCAchievement(578, "Fake it till you bake it", -1, 6),
    CCAchievement(579, "History in the baking", -1, 6),
    CCAchievement(586, "What do you get for the baker who has everything", -1, 6),
    CCAchievement(587, "Bottomless pit", -1, 6),
    CCAchievement(592, "Rainy day fund", -1, 6),
    CCAchievement(593, "And a little extra", -1, 6),

    # CpS
    CCAchievement(16, "Casual baking", -1, 0),
    CCAchievement(17, "Hardcore baking", -1, 0),
    CCAchievement(18, "Steady tasty stream", -1, 0),
    CCAchievement(19, "Cookie monster", -1, 0),
    CCAchievement(20, "Mass producer", -1, 0),
    CCAchievement(21, "Cookie vortex", -1, 1),
    CCAchievement(22, "Cookie pulsar", -1, 1),
    CCAchievement(23, "Cookie quasar", -1, 1),
    CCAchievement(24, "Oh hey, you're still here", -1, 2),
    CCAchievement(25, "Let's never bake again", -1, 2),
    CCAchievement(231, "A world filled with cookies", -1, 3),
    CCAchievement(232, "When this baby hits 36 quadrillion cookies per hour", -1, 4),
    CCAchievement(233, "Fast and delicious", -1, 5),
    CCAchievement(234, "Cookiehertz : a really, really tasty hertz", -1, 5),
    CCAchievement(235, "Woops, you solved world hunger", -1, 6),
    CCAchievement(236, "Turbopuns", -1, 6),
    CCAchievement(237, "Faster menner", -1, 6),
    CCAchievement(238, "And yet you're still hungry", -1, 6),
    CCAchievement(239, "The Abakening", -1, 6),
    CCAchievement(240,
                  "There's really no hard limit to how long these achievement names can be and to be quite honest I'm rather curious to see how far we can go.<br>Adolphus W. Green (1844–1917) started as the Principal of the Groton School in 1864. By 1865, he became second assistant librarian at the New York Mercantile Library; from 1867 to 1869, he was promoted to full librarian. From 1869 to 1873, he worked for Evarts, Southmayd & Choate, a law firm co-founded by William M. Evarts, Charles Ferdinand Southmayd and Joseph Hodges Choate. He was admitted to the New York State Bar Association in 1873.<br>Anyway, how's your day been?",
                  -1, 6),
    CCAchievement(241, "Fast", -1, 6),
    CCAchievement(274, "Knead for speed", -1, 6),
    CCAchievement(275, "Well the cookies start coming and they don't stop coming", -1, 6),
    CCAchievement(276, "I don't know if you've noticed but all these icons are very slightly off-center", -1,
                  6),
    CCAchievement(277, "The proof of the cookie is in the baking", -1, 6),
    CCAchievement(278, "If it's worth doing, it's worth overdoing", -1, 6),
    CCAchievement(368, "Running with scissors", -1, 6),
    CCAchievement(369, "Rarefied air", -1, 6),
    CCAchievement(370, "Push it to the limit", -1, 6),
    CCAchievement(371, "Green cookies sleep furiously", -1, 6),
    CCAchievement(388, "Leisurely pace", -1, 6),
    CCAchievement(389, "Hypersonic", -1, 6),
    CCAchievement(428, "Gotta go fast", -1, 6),
    CCAchievement(448, "Bake him away, toys", -1, 6),
    CCAchievement(449, "You're #1 so why try harder", -1, 6),
    CCAchievement(450, "Haven't even begun to peak", -1, 6),
    CCAchievement(467, "What did we even eat before these", -1, 6),
    CCAchievement(468, "Heavy flow", -1, 6),
    CCAchievement(469, "More you say?", -1, 6),
    CCAchievement(531, "Keep going until I say stop", -1, 6),
    CCAchievement(532, "But I didn't say stop, did I?", -1, 6),
    CCAchievement(533, "With unrivaled fervor", -1, 6),
    CCAchievement(576, "I am speed", -1, 6),
    CCAchievement(577, "And on and on", -1, 6),
    CCAchievement(584, "Everything happens so much", -1, 6),
    CCAchievement(585, "I'll rest when I'm dead", -1, 6),
    CCAchievement(590, "Can we get much higher", -1, 6),
    CCAchievement(591, "Speed's the name of the game (no it's not it's called Cookie Clicker)", -1, 6),

    # Click & buildings
    CCAchievement(30, "Clicktastic", -1, 0),
    CCAchievement(31, "Clickathlon", -1, 1),
    CCAchievement(32, "Clickolympics", -1, 2),
    CCAchievement(33, "Clickorama", -1, 3),
    CCAchievement(100, "Clickasmic", -1, 4),
    CCAchievement(145, "Clickageddon", -1, 5),
    CCAchievement(146, "Clicknarok", -1, 6),
    CCAchievement(244, "Clickastrophe", -1, 6),
    CCAchievement(245, "Clickataclysm", -1, 6),
    CCAchievement(337, "The ultimate clickdown", -1, 6),
    CCAchievement(376, "All the other kids with the pumped up clicks", -1, 6),
    CCAchievement(377, "One...more...click...", -1, 6),
    CCAchievement(473, "Clickety split", -1, 6),
    CCAchievement(574, "Ain't that a click in the head", -1, 6),
    CCAchievement(640, "What's not clicking", -1, 6),
    CCAchievement(34, "Click", 0, 0),
    CCAchievement(35, "Double-click", 0, 0),
    CCAchievement(36, "Mouse wheel", 0, 0),
    CCAchievement(37, "Of Mice and Men", 0, 0),
    CCAchievement(38, "The Digital", 0, 1),
    CCAchievement(147, "Extreme polydactyly", 0, 2),
    CCAchievement(148, "Dr. T", 0, 3),
    CCAchievement(246, "Thumbs, phalanges, metacarpals", 0, 4),
    CCAchievement(398, "With her finger and her thumb", 0, 5),
    CCAchievement(474, "Gotta hand it to you", 0, 6),
    CCAchievement(493, "The devil's workshop", 0, 6),
    CCAchievement(641, "All on deck", 0, 6),
    CCAchievement(642, "A round of applause", 0, 6),
    CCAchievement(134, "Click delegator", 0, 5),
    CCAchievement(189, "Finger clickin' good", 0, 5),
    CCAchievement(293, "Click (starring Adam Sandler)", 0, 5),
    CCAchievement(307, "Freaky jazz hands", 0, 2),
    CCAchievement(39, "Just wrong", 1, 0),
    CCAchievement(81, "Elder", -1, 2),
    CCAchievement(431, "Veteran", -1, 3),
    CCAchievement(248, "The elder scrolls", 0, 4),
    CCAchievement(40, "Grandma's cookies", 1, 0),
    CCAchievement(41, "Sloppy kisses", 1, 0),
    CCAchievement(42, "Retirement home", 1, 1),
    CCAchievement(101, "Friend of the ancients", 1, 2),
    CCAchievement(102, "Ruler of the ancients", 1, 3),
    CCAchievement(149, "The old never bothered me anyway", 1, 4),
    CCAchievement(208, "The agemaster", 1, 5),
    CCAchievement(209, "To oldly go", 1, 6),
    CCAchievement(338, "Aged well", 1, 6),
    CCAchievement(339, "101st birthday", 1, 6),
    CCAchievement(340, "But wait 'til you get older", 1, 6),
    CCAchievement(399, "Defense of the ancients", 1, 6),
    CCAchievement(475, "Okay boomer", 1, 6),
    CCAchievement(556, "They moistly come at night", 1, 6),
    CCAchievement(618, "And now you're even older", 1, 6),
    CCAchievement(135, "Gushing grannies", 1, 5),
    CCAchievement(190, "Panic at the bingo", 1, 5),
    CCAchievement(294, "Frantiquities", 1, 5),
    CCAchievement(308, "Methuselah", 1, 2),
    CCAchievement(43, "Bought the farm", 2, 0),
    CCAchievement(44, "Reap what you sow", 2, 0),
    CCAchievement(45, "Farm ill", 2, 1),
    CCAchievement(115, "Perfected agriculture", 2, 2),
    CCAchievement(150, "Homegrown", 2, 3),
    CCAchievement(210, "Gardener extraordinaire", 2, 4),
    CCAchievement(250, "Seedy business", 2, 5),
    CCAchievement(281, "You and the beanstalk", 2, 6),
    CCAchievement(341, "Harvest moon", 2, 6),
    CCAchievement(354, "Make like a tree", 2, 6),
    CCAchievement(400, "Sharpest tool in the shed", 2, 6),
    CCAchievement(476, "Overripe", 2, 6),
    CCAchievement(494, "In the green", 2, 6),
    CCAchievement(557, "It's grown on you", 2, 6),
    CCAchievement(619, "Au naturel", 2, 6),
    CCAchievement(136, "I hate manure", 2, 5),
    CCAchievement(191, "Rake in the dough", 2, 5),
    CCAchievement(295, "Overgrowth", 2, 5),
    CCAchievement(309, "Huge tracts of land", 2, 3),
    CCAchievement(49, "You know the drill", 3, 0),
    CCAchievement(50, "Excavation site", 3, 0),
    CCAchievement(51, "Hollow the planet", 3, 1),
    CCAchievement(117, "Can you dig it", 3, 2),
    CCAchievement(152, "The center of the Earth", 3, 3),
    CCAchievement(211, "Tectonic ambassador", 3, 4),
    CCAchievement(251, "Freak fracking", 3, 5),
    CCAchievement(282, "Romancing the stone", 3, 6),
    CCAchievement(342, "Mine?", 3, 6),
    CCAchievement(355, "Cave story", 3, 6),
    CCAchievement(401, "Hey now, you're a rock", 3, 6),
    CCAchievement(477, "Rock on", 3, 6),
    CCAchievement(495, "Mountain out of a molehill, but like in a good way", 3, 6),
    CCAchievement(558, "Don't let the walls cave in on you", 3, 6),
    CCAchievement(620, "Dirt-rich", 3, 6),
    CCAchievement(137, "Never dig down", 3, 5),
    CCAchievement(192, "Quarry on", 3, 5),
    CCAchievement(296, "Sedimentalism", 3, 5),
    CCAchievement(310, "D-d-d-d-deeper", 3, 3),
    CCAchievement(46, "Production chain", 4, 0),
    CCAchievement(47, "Industrial revolution", 4, 0),
    CCAchievement(48, "Global warming", 4, 1),
    CCAchievement(116, "Ultimate automation", 4, 2),
    CCAchievement(151, "Technocracy", 4, 3),
    CCAchievement(212, "Rise of the machines", 4, 4),
    CCAchievement(252, "Modern times", 4, 5),
    CCAchievement(283, "Ex machina", 4, 6),
    CCAchievement(343, "In full gear", 4, 6),
    CCAchievement(356, "In-cog-neato", 4, 6),
    CCAchievement(402, "Break the mold", 4, 6),
    CCAchievement(478, "Self-manmade man", 4, 6),
    CCAchievement(496, "The wheels of progress", 4, 6),
    CCAchievement(559, "Replaced by robots", 4, 6),
    CCAchievement(621, "Bots build bots", 4, 6),
    CCAchievement(138, "The incredible machine", 4, 5),
    CCAchievement(193, "Yes I love technology", 4, 5),
    CCAchievement(297, "Labor of love", 4, 5),
    CCAchievement(311, "Patently genius", 4, 3),
    CCAchievement(171, "Pretty penny", 5, 0),
    CCAchievement(172, "Fit the bill", 5, 1),
    CCAchievement(173, "A loan in the dark", 5, 2),
    CCAchievement(174, "Need for greed", 5, 3),
    CCAchievement(175, "It's the economy, stupid", 5, 4),
    CCAchievement(213, "Acquire currency", 5, 5),
    CCAchievement(253, "The nerve of war", 5, 6),
    CCAchievement(284, "And I need it now", 5, 6),
    CCAchievement(344, "Treacle tart economics", 5, 6),
    CCAchievement(357, "Save your breath because that's all you've got left", 5, 6),
    CCAchievement(403, "Get the show on, get paid", 5, 6),
    CCAchievement(479, "Checks out", 5, 6),
    CCAchievement(497, "That's rich", 5, 6),
    CCAchievement(560, "Financial prodigy", 5, 6),
    CCAchievement(622, "Getting that bag", 5, 6),
    CCAchievement(186, "Vested interest", 5, 5),
    CCAchievement(194, "Paid in full", 5, 5),
    CCAchievement(298, "Reverse funnel system", 5, 5),
    CCAchievement(312, "A capital idea", 5, 3),
    CCAchievement(176, "Your time to shrine", 6, 0),
    CCAchievement(177, "Shady sect", 6, 1),
    CCAchievement(178, "New-age cult", 6, 2),
    CCAchievement(179, "Organized religion", 6, 3),
    CCAchievement(180, "Fanaticism", 6, 4),
    CCAchievement(214, "Zealotry", 6, 5),
    CCAchievement(254, "Wololo", 6, 6),
    CCAchievement(285, "Pray on the weak", 6, 6),
    CCAchievement(345, "Holy cookies, grandma!", 6, 6),
    CCAchievement(358, "Vengeful and almighty", 6, 6),
    CCAchievement(404, "My world's on fire, how about yours", 6, 6),
    CCAchievement(480, "Living on a prayer", 6, 6),
    CCAchievement(498, "Preaches and cream", 6, 6),
    CCAchievement(561, "And I will pray to a big god", 6, 6),
    CCAchievement(623, "The leader is good, the leader is great", 6, 6),
    CCAchievement(187, "New world order", 6, 5),
    CCAchievement(195, "Church of Cookiology", 6, 5),
    CCAchievement(299, "Thus spoke you", 6, 5),
    CCAchievement(313, "It belongs in a bakery", 6, 4),
    CCAchievement(181, "Bewitched", 7, 0),
    CCAchievement(182, "The sorcerer's apprentice", 7, 1),
    CCAchievement(183, "Charms and enchantments", 7, 2),
    CCAchievement(184, "Curses and maledictions", 7, 3),
    CCAchievement(185, "Magic kingdom", 7, 4),
    CCAchievement(215, "The wizarding world", 7, 5),
    CCAchievement(255, "And now for my next trick, I'll need a volunteer from the audience", 7, 6),
    CCAchievement(286, "It's a kind of magic", 7, 6),
    CCAchievement(346, "The Prestige", 7, 6),
    CCAchievement(359, "Spell it out for you", 7, 6),
    CCAchievement(405, "The meteor men beg to differ", 7, 6),
    CCAchievement(481, "Higitus figitus migitus mum", 7, 6),
    CCAchievement(499, "Magic thinking", 7, 6),
    CCAchievement(562, "Shosple Colupis", 7, 6),
    CCAchievement(624, "You don't think they could've used... it couldn't have been ma-", 7, 6),
    CCAchievement(188, "Hocus pocus", 7, 5),
    CCAchievement(196, "Too many rabbits, not enough hats", 7, 5),
    CCAchievement(300, "Manafest destiny", 7, 5),
    CCAchievement(314, "Motormouth", 7, 4),
    CCAchievement(52, "Expedition", 8, 1),
    CCAchievement(53, "Galactic highway", 8, 1),
    CCAchievement(54, "Far far away", 8, 2),
    CCAchievement(118, "Type II civilization", 8, 3),
    CCAchievement(153, "We come in peace", 8, 4),
    CCAchievement(216, "Parsec-masher", 8, 5),
    CCAchievement(256, "It's not delivery", 8, 6),
    CCAchievement(287, "Make it so", 8, 6),
    CCAchievement(347, "That's just peanuts to space", 8, 6),
    CCAchievement(360, "Space space space space space", 8, 6),
    CCAchievement(406, "Only shooting stars", 8, 6),
    CCAchievement(482, "The incredible journey", 8, 6),
    CCAchievement(500, "Is there life on Mars?", 8, 6),
    CCAchievement(563, "False vacuum", 8, 6),
    CCAchievement(625, "Signed, sealed, delivered", 8, 6),
    CCAchievement(139, "And beyond", 8, 5),
    CCAchievement(197, "The most precious cargo", 8, 5),
    CCAchievement(301, "Neither snow nor rain nor heat nor gloom of night", 8, 5),
    CCAchievement(315, "Been there done that", 8, 4),
    CCAchievement(55, "Transmutation", 9, 1),
    CCAchievement(56, "Transmogrification", 9, 1),
    CCAchievement(57, "Gold member", 9, 2),
    CCAchievement(119, "Gild wars", 9, 3),
    CCAchievement(154, "The secrets of the universe", 9, 4),
    CCAchievement(217, "The work of a lifetime", 9, 5),
    CCAchievement(257, "Gold, Jerry! Gold!", 9, 6),
    CCAchievement(288, "All that glitters is gold", 9, 6),
    CCAchievement(348, "Worth its weight in lead", 9, 6),
    CCAchievement(361, "Don't get used to yourself, you're gonna have to change", 9, 6),
    CCAchievement(407, "We could all use a little change", 9, 6),
    CCAchievement(483, "Just a phase", 9, 6),
    CCAchievement(501, "Bad chemistry", 9, 6),
    CCAchievement(564, "Metallic taste", 9, 6),
    CCAchievement(626, "Sugar, spice, and everything nice", 9, 6),
    CCAchievement(140, "Magnum Opus", 9, 5),
    CCAchievement(198, "The Aureate", 9, 5),
    CCAchievement(302, "I've got the Midas touch", 9, 5),
    CCAchievement(316, "Phlogisticated substances", 9, 4),
    CCAchievement(58, "A whole new world", 10, 1),
    CCAchievement(59, "Now you're thinking", 10, 2),
    CCAchievement(60, "Dimensional shift", 10, 3),
    CCAchievement(120, "Brain-split", 10, 4),
    CCAchievement(155, "Realm of the Mad God", 10, 5),
    CCAchievement(218, "A place lost in time", 10, 6),
    CCAchievement(258, "Forbidden zone", 10, 6),
    CCAchievement(289,
                  "H̸̷͓̳̳̯̟͕̟͍͍̣͡ḛ̢̦̰̺̮̝͖͖̘̪͉͘͡ ̠̦͕̤̪̝̥̰̠̫̖̣͙̬͘ͅC̨̦̺̩̲̥͉̭͚̜̻̝̣̼͙̮̯̪o̴̡͇̘͎̞̲͇̦̲͞͡m̸̩̺̝̣̹̱͚̬̥̫̳̼̞̘̯͘ͅẹ͇̺̜́̕͢s̶̙̟̱̥̮̯̰̦͓͇͖͖̝͘͘͞",
                  10, 6),
    CCAchievement(349, "What happens in the vortex stays in the vortex", 10, 6),
    CCAchievement(362, "Objects in the mirror dimension are closer than they appear", 10, 6),
    CCAchievement(408, "Your brain gets smart but your head gets dumb", 10, 6),
    CCAchievement(484, "Don't let me leave, Murph", 10, 6),
    CCAchievement(502, "Reduced to gibbering heaps", 10, 6),
    CCAchievement(565, "Swiss cheese", 10, 6),
    CCAchievement(627, "Not even remotely close to Kansas anymore", 10, 6),
    CCAchievement(141, "With strange eons", 10, 5),
    CCAchievement(199, "Ever more hideous", 10, 5),
    CCAchievement(303, "Which eternal lie", 10, 5),
    CCAchievement(317, "Bizarro world", 10, 5),
    CCAchievement(61, "Time warp", 11, 2),
    CCAchievement(62, "Alternate timeline", 11, 2),
    CCAchievement(63, "Rewriting history", 11, 3),
    CCAchievement(121, "Time duke", 11, 4),
    CCAchievement(156, "Forever and ever", 11, 5),
    CCAchievement(219, "Heat death", 11, 6),
    CCAchievement(259,
                  "cookie clicker forever and forever a hundred years cookie clicker, all day long forever, forever a hundred times, over and over cookie clicker adventures dot com",
                  11, 6),
    CCAchievement(290, "Way back then", 11, 6),
    CCAchievement(350, "Invited to yesterday's party", 11, 6),
    CCAchievement(363, "Groundhog day", 11, 6),
    CCAchievement(409, "The years start coming", 11, 6),
    CCAchievement(485, "Caveman to cosmos", 11, 6),
    CCAchievement(503, "Back already?", 11, 6),
    CCAchievement(566, "But the future refused to change", 11, 6),
    CCAchievement(628, "I only meant to stay a while", 11, 6),
    CCAchievement(142, "Spacetime jigamaroo", 11, 5),
    CCAchievement(200, "Be kind, rewind", 11, 5),
    CCAchievement(304, "Déjà vu", 11, 5),
    CCAchievement(318, "The long now", 11, 5),
    CCAchievement(87, "Antibatter", 12, 2),
    CCAchievement(88, "Quirky quarks", 12, 2),
    CCAchievement(89, "It does matter!", 12, 3),
    CCAchievement(122, "Molecular maestro", 12, 4),
    CCAchievement(157, "Walk the planck", 12, 5),
    CCAchievement(220, "Microcosm", 12, 6),
    CCAchievement(260, "Scientists baffled everywhere", 12, 6),
    CCAchievement(291, "Exotic matter", 12, 6),
    CCAchievement(351, "Downsizing", 12, 6),
    CCAchievement(364, "A matter of perspective", 12, 6),
    CCAchievement(410, "What a concept", 12, 6),
    CCAchievement(486, "Particular tastes", 12, 6),
    CCAchievement(504, "Nuclear throne", 12, 6),
    CCAchievement(567, "What's the dark matter with you", 12, 6),
    CCAchievement(629, "Not 20 years away forever", 12, 6),
    CCAchievement(143, "Supermassive", 12, 5),
    CCAchievement(201, "Infinitesimal", 12, 5),
    CCAchievement(305, "Powers of Ten", 12, 5),
    CCAchievement(319, "Chubby hadrons", 12, 5),
    CCAchievement(123, "Lone photon", 13, 2),
    CCAchievement(124, "Dazzling glimmer", 13, 3),
    CCAchievement(125, "Blinding flash", 13, 4),
    CCAchievement(126, "Unending glow", 13, 5),
    CCAchievement(158, "Rise and shine", 13, 6),
    CCAchievement(221, "Bright future", 13, 6),
    CCAchievement(261, "Harmony of the spheres", 13, 6),
    CCAchievement(292, "At the end of the tunnel", 13, 6),
    CCAchievement(352, "My eyes", 13, 6),
    CCAchievement(365, "Optical illusion", 13, 6),
    CCAchievement(411, "You'll never shine if you don't glow", 13, 6),
    CCAchievement(487, "A light snack", 13, 6),
    CCAchievement(505, "Making light of the situation", 13, 6),
    CCAchievement(568, "Enlightenment", 13, 6),
    CCAchievement(630, "Bright side of the Moon", 13, 6),
    CCAchievement(144, "Praise the sun", 13, 5),
    CCAchievement(202, "A still more glorious dawn", 13, 5),
    CCAchievement(306, "Now the dark days are gone", 13, 5),
    CCAchievement(320, "Palettable", 13, 5),
    CCAchievement(325, "Lucked out", 14, 2),
    CCAchievement(326, "What are the odds", 14, 3),
    CCAchievement(327, "Grandma needs a new pair of shoes", 14, 4),
    CCAchievement(328, "Million to one shot, doc", 14, 5),
    CCAchievement(329, "As luck would have it", 14, 6),
    CCAchievement(330, "Ever in your favor", 14, 6),
    CCAchievement(331, "Be a lady", 14, 6),
    CCAchievement(332, "Dicey business", 14, 6),
    CCAchievement(353, "Maybe a chance in hell, actually", 14, 6),
    CCAchievement(366, "Jackpot", 14, 6),
    CCAchievement(412, "You'll never know if you don't go", 14, 6),
    CCAchievement(488, "Tempting fate", 14, 6),
    CCAchievement(506, "Flip a cookie. Chips, I win. Crust, you lose.", 14, 6),
    CCAchievement(569, "Never tell me the odds", 14, 6),
    CCAchievement(631, "Riding the Mersenne twister", 14, 6),
    CCAchievement(333, "Fingers crossed", 14, 5),
    CCAchievement(334, "Just a statistic", 14, 5),
    CCAchievement(335, "Murphy's wild guess", 14, 5),
    CCAchievement(336, "Let's leaf it at that", 14, 6),
    CCAchievement(413, "Self-contained", 15, 2),
    CCAchievement(414, "Threw you for a loop", 15, 3),
    CCAchievement(415, "The sum of its parts", 15, 4),
    CCAchievement(416, "Bears repeating", 15, 5),
    CCAchievement(417, "More of the same", 15, 6),
    CCAchievement(418, "Last recurse", 15, 6),
    CCAchievement(419, "Out of one, many", 15, 6),
    CCAchievement(420, "An example of recursion", 15, 6),
    CCAchievement(421, "For more information on this achievement, please refer to its title", 15, 6),
    CCAchievement(422, "I'm so meta, even this achievement", 15, 6),
    CCAchievement(423, "Never get bored", 15, 6),
    CCAchievement(489, "Tautological", 15, 6),
    CCAchievement(507, "In and of itself", 15, 6),
    CCAchievement(570, "Blowing an Apollonian gasket", 15, 6),
    CCAchievement(632, "Divide and conquer", 15, 6),
    CCAchievement(424, "The needs of the many", 15, 5),
    CCAchievement(425, "Eating its own", 15, 5),
    CCAchievement(426, "We must go deeper", 15, 5),
    CCAchievement(427, "Sierpinski rhomboids", 15, 6),
    CCAchievement(433, "F12", 16, 3),
    CCAchievement(434, "Variable success", 16, 4),
    CCAchievement(435, "No comments", 16, 5),
    CCAchievement(436, "Up to code", 16, 6),
    CCAchievement(437, "Works on my machine", 16, 6),
    CCAchievement(438, "Technical debt", 16, 6),
    CCAchievement(439, "Mind your language", 16, 6),
    CCAchievement(440, "Inconsolable", 16, 6),
    CCAchievement(441, "Closure", 16, 6),
    CCAchievement(442,
                  "Dude what if we're all living in a simulation like what if we're all just code on a computer somewhere",
                  16, 6),
    CCAchievement(443, "Taking the back streets", 16, 6),
    CCAchievement(490, "Curly braces", 16, 6),
    CCAchievement(508, "Duck typing", 16, 6),
    CCAchievement(571, "Get with the program", 16, 6),
    CCAchievement(633, "Pebcakes", 16, 6),
    CCAchievement(444, "Inherited prototype", 16, 5),
    CCAchievement(445, "A model of document object", 16, 5),
    CCAchievement(446, "First-class citizen", 16, 5),
    CCAchievement(447, "Alexandria", 16, 6),
    CCAchievement(509, "They'll never know what hit 'em", 17, 4),
    CCAchievement(510, "Well-versed", 17, 5),
    CCAchievement(511, "Ripe for the picking", 17, 6),
    CCAchievement(512, "Unreal", 17, 6),
    CCAchievement(513, "Once you've seen one", 17, 6),
    CCAchievement(514, "Spoils and plunder", 17, 6),
    CCAchievement(515, "Nobody exists on purpose, nobody belongs anywhere", 17, 6),
    CCAchievement(516, "Hyperspace expressway", 17, 6),
    CCAchievement(517, "Versatile", 17, 6),
    CCAchievement(518, "You are inevitable", 17, 6),
    CCAchievement(519, "Away from this place", 17, 6),
    CCAchievement(520, "Everywhere at once", 17, 6),
    CCAchievement(521, "Reject reality, substitute your own", 17, 6),
    CCAchievement(572, "Lost your cosmic marbles", 17, 6),
    CCAchievement(634, "Greener on the other sides", 17, 6),
    CCAchievement(522, "Fringe", 17, 5),
    CCAchievement(523, "Coherence", 17, 5),
    CCAchievement(524, "Earth-616", 17, 5),
    CCAchievement(525, "Strange topologies", 17, 6),
    CCAchievement(539, "It's big brain time", 18, 5),
    CCAchievement(540, "Just my imagination", 18, 6),
    CCAchievement(541, "Now there's an idea", 18, 6),
    CCAchievement(542, "The organ that named itself", 18, 6),
    CCAchievement(543, "Gyrification", 18, 6),
    CCAchievement(544, "A trademarked portmanteau of \"imagination\" and \"engineering\"", 18, 6),
    CCAchievement(545, "Mindfulness", 18, 6),
    CCAchievement(546, "The 10% myth", 18, 6),
    CCAchievement(547, "Don't think about it too hard", 18, 6),
    CCAchievement(548, "Though fools seldom differ", 18, 6),
    CCAchievement(549, "Looking kind of dumb", 18, 6),
    CCAchievement(550, "A beautiful mind", 18, 6),
    CCAchievement(551, "Cardinal synapses", 18, 6),
    CCAchievement(573, "By will alone I set my mind in motion", 18, 6),
    CCAchievement(635, "Where is my mind", 18, 6),
    CCAchievement(552, "Positive thinking", 18, 5),
    CCAchievement(553, "The thought that counts", 18, 5),
    CCAchievement(554, "Unthinkable", 18, 5),
    CCAchievement(555, "Gifted", 18, 6),
    CCAchievement(600, "My own clone", 19, 6),
    CCAchievement(601, "Multiplicity", 19, 6),
    CCAchievement(602, "Born for this job", 19, 6),
    CCAchievement(603, "Episode II", 19, 6),
    CCAchievement(604, "Copy that", 19, 6),
    CCAchievement(605, "Life finds a way", 19, 6),
    CCAchievement(606, "Overcrowding", 19, 6),
    CCAchievement(607, "Strength in numbers", 19, 6),
    CCAchievement(608, "Army of me", 19, 6),
    CCAchievement(609, "Know thyself", 19, 6),
    CCAchievement(610, "Didn't make sense not to live", 19, 6),
    CCAchievement(611, "Genetic bottleneck", 19, 6),
    CCAchievement(612, "Despite everything, it's still you", 19, 6),
    CCAchievement(613, "Everyone everywhere all at once", 19, 6),
    CCAchievement(636, "Introspection", 19, 6),
    CCAchievement(614, "Self-made", 19, 6),
    CCAchievement(615, "Reproducible results", 19, 6),
    CCAchievement(616, "That's all you", 19, 6),
    CCAchievement(617, "Self-improvement", 19, 6),

    # Others
    CCAchievement(72, "Builder", -1, 0),
    CCAchievement(73, "Architect", -1, 1),
    CCAchievement(83, "Engineer", -1, 2),
    CCAchievement(127, "Lord of Constructs", -1, 3),
    CCAchievement(526, "Grand design", -1, 5),
    CCAchievement(527, "Ecumenopolis", -1, 6),
    CCAchievement(581, "Myriad", -1, 6),
    CCAchievement(74, "Enhancer", -1, 0),
    CCAchievement(75, "Augmenter", -1, 0),
    CCAchievement(90, "Upgrader", -1, 2),
    CCAchievement(128, "Lord of Progress", -1, 3),
    CCAchievement(528, "The full picture", -1, 5),
    CCAchievement(529, "When there's nothing left to add", -1, 5),
    CCAchievement(582, "Kaizen", -1, 6),
    CCAchievement(583, "Beyond quality", -1, 6),
    CCAchievement(638, "Oft we mar what's well", -1, 6),
    CCAchievement(588, "All the stars in heaven", -1, 6),
    CCAchievement(247, "Polymath", -1, 5),
    CCAchievement(430, "Renaissance baker", -1, 6),
    CCAchievement(64, "One with everything", -1, 6),
    CCAchievement(65, "Mathematician", -1, 6),
    CCAchievement(66, "Base 10", -1, 6),
    CCAchievement(91, "Centennial", -1, 10),
    CCAchievement(131, "Centennial and a half", -1, 10),
    CCAchievement(129, "Bicentennial", -1, 10),
    CCAchievement(242, "Bicentennial and a half", -1, 10),
    CCAchievement(273, "Tricentennial", -1, 10),
    CCAchievement(392, "Tricentennial and a half", -1, 10),
    CCAchievement(393, "Quadricentennial", -1, 10),
    CCAchievement(394, "Quadricentennial and a half", -1, 10),
    CCAchievement(395, "Quincentennial", -1, 10),
    CCAchievement(466, "Quincentennial and a half", -1, 10),
    CCAchievement(530, "Sexcentennial", -1, 10),
    CCAchievement(575, "Sexcentennial and a half", -1, 10),
    CCAchievement(599, "Septcentennial", -1, 10),
    CCAchievement(67, "Golden cookie", -1, 0),
    CCAchievement(68, "Lucky cookie", -1, 0),
    CCAchievement(69, "A stroke of luck", -1, 0),
    CCAchievement(77, "Fortune", -1, 1),
    CCAchievement(84, "Leprechaun", -1, 4),
    CCAchievement(85, "Black cat's paw", -1, -1),
    CCAchievement(263, "Early bird", -1, 0),
    CCAchievement(264, "Fading luck", -1, 0),
    CCAchievement(324, "Four-leaf cookie", -1, 4),
    CCAchievement(432, "Thick-skinned", -1, 6),
    CCAchievement(465, "Jellicles", -1, 6),
    CCAchievement(491, "Seven horseshoes", -1, -1),
    CCAchievement(76, "Cookie-dunker", -1, 0),
    CCAchievement(132, "Tiny cookie", -1, 0),
    CCAchievement(170, "What's in a name", -1, 0),
    CCAchievement(204, "Here you go", -1, 0),
    CCAchievement(243, "Tabloid addiction", -1, 0),
    CCAchievement(538, "Stifling the press", -1, 0),
    CCAchievement(492, "Olden days", -1, 0),
    CCAchievement(29, "Neverclick", -1, 4),
    CCAchievement(71, "Uncanny clicker", -1, 0),
    CCAchievement(594, "Grandmapocalypse", -1, 66),
    CCAchievement(595, "Wrath cookie", -1, 66),
    CCAchievement(79, "Elder nap", -1, 66),
    CCAchievement(80, "Elder slumber", -1, 66),
    CCAchievement(82, "Elder calm", -1, 66),
    CCAchievement(598, "Wrinkler poker", -1, 66),
    CCAchievement(105, "Itchscratcher", -1, 66),
    CCAchievement(106, "Wrinklesquisher", -1, 66),
    CCAchievement(107, "Moistburster", -1, 66),
    CCAchievement(266, "Dude, sweet", -1, 0),
    CCAchievement(267, "Sugar rush", -1, 1),
    CCAchievement(268, "Year's worth of cavities", -1, -1),
    CCAchievement(269, "Hand-picked", -1, 1),
    CCAchievement(270, "Sugar sugar", -1, 3),
    CCAchievement(271, "All-natural cane sugar", -1, -1),
    CCAchievement(272, "Sweetmeats", -1, 66),
    CCAchievement(396, "Maillard reaction", -1, 6),
    CCAchievement(108, "Spooky cookies", -1, 10),
    CCAchievement(109, "Coming to town", -1, 10),
    CCAchievement(110, "All hail Santa", -1, 10),
    CCAchievement(111, "Let it snow", -1, 3),
    CCAchievement(112, "Oh deer", -1, 3),
    CCAchievement(113, "Sleigh of hand", -1, 3),
    CCAchievement(114, "Reindeer sleigher", -1, 4),
    CCAchievement(265, "Eldeer", -1, 66),
    CCAchievement(580, "Baby it's old outside", -1, 3),
    CCAchievement(130, "Lovely cookies", -1, 3),
    CCAchievement(166, "The hunt is on", -1, 3),
    CCAchievement(167, "Egging on", -1, 3),
    CCAchievement(168, "Mass Easteria", -1, 4),
    CCAchievement(169, "Hide & seek champion", -1, 5),
    CCAchievement(222, "Here be dragon", -1, 10),
    CCAchievement(203, "Rebirth", -1, 1),
    CCAchievement(205, "Resurrection", -1, 3),
    CCAchievement(206, "Reincarnation", -1, 6),
    CCAchievement(207, "Endless cycle", -1, -1),
    CCAchievement(26, "Sacrifice", -1, 0),
    CCAchievement(27, "Oblivion", -1, 0),
    CCAchievement(28, "From scratch", -1, 1),
    CCAchievement(86, "Nihilism", -1, 2),
    CCAchievement(161, "Dematerialize", -1, 2),
    CCAchievement(162, "Nil zero zilch", -1, 3),
    CCAchievement(163, "Transcendence", -1, 4),
    CCAchievement(164, "Obliterate", -1, 5),
    CCAchievement(165, "Negative void", -1, 6),
    CCAchievement(249, "To crumbs, you say?", -1, 6),
    CCAchievement(383, "You get nothing", -1, 6),
    CCAchievement(384, "Humble rebeginnings", -1, 6),
    CCAchievement(385, "The end of the world", -1, 6),
    CCAchievement(386, "Oh, you're back", -1, 6),
    CCAchievement(387, "Lazarus", -1, 6),
    CCAchievement(454, "Smurf account", -1, 6),
    CCAchievement(455, "If at first you don't succeed", -1, 10),
    CCAchievement(596, "No more room in hell", -1, 10),
    CCAchievement(70, "Cheated cookies taste awful", -1, 0),
    CCAchievement(159, "God complex", -1, 0),
    CCAchievement(160, "Third-party", -1, -1),
    CCAchievement(397, "When the cookies ascend just right", -1, -1),
    CCAchievement(92, "Hardcore", -1, 1),
    CCAchievement(93, "Speed baking I", -1, 1),
    CCAchievement(94, "Speed baking II", -1, 1),
    CCAchievement(95, "Speed baking III", -1, 1),
    CCAchievement(78, "True Neverclick", -1, 1),
    CCAchievement(103, "Wholesome", -1, 1),
    CCAchievement(589, "No time like the present", -1, 6),
    CCAchievement(597, "In her likeness", 19, 6),
    CCAchievement(104, "Just plain lucky", -1, 10),
    CCAchievement(456, "O Fortuna", -1, 10),
    CCAchievement(262, "Last Chance to See", -1, -1),
    CCAchievement(367, "So much to do so much to see", -1, -1),
    CCAchievement(96, "Getting even with the oven", -1, -1),
    CCAchievement(97, "Now this is pod-smashing", -1, -1),
    CCAchievement(98, "Chirped out", -1, -1),
    CCAchievement(99, "Follow the white rabbit", -1, -1),
    CCAchievement(321, "Bibbidi-bobbidi-boo", 7, 1),
    CCAchievement(322, "I'm the wiz", 7, 4),
    CCAchievement(323, "A wizard is you", -1, -1),
    CCAchievement(378, "Botany enthusiast", 2, 3),
    CCAchievement(379, "Green, aching thumb", -1, -1),
    CCAchievement(380, "In the garden of Eden (baby)", -1, 3),
    CCAchievement(381, "Keeper of the conservatory", -1, -1),
    CCAchievement(382, "Seedless to nay", -1, -1),
    CCAchievement(457, "Initial public offering", -1, 1),
    CCAchievement(458, "Rookie numbers", -1, 10),
    CCAchievement(459, "No nobility in poverty", -1, 10),
    CCAchievement(460, "Full warehouses", -1, 5),
    CCAchievement(461, "Make my day", -1, 4),
    CCAchievement(462, "Buy buy buy", -1, 4),
    CCAchievement(463, "Gaseous assets", -1, -1),
    CCAchievement(464, "Pyramid scheme", -1, 10),
    CCAchievement(537, "Liquid assets", -1, 10),
    CCAchievement(637, "Debt evasion", -1, 2),
    CCAchievement(133, "You win a cookie", -1, 2),
    CCAchievement(639, "Cookie Clicker", 19, 5),
]

valid_locations = list(filter(lambda achv: achv.sphere != SPHERE.EXCLUDED.value, achievements))

locations = {
    'all': achievements,
    'valid': valid_locations,
    'by_building': { building: list(filter( lambda achv: achv.building == building.value, valid_locations )) for building in BUILDING },
    'by_sphere': { sphere: list(filter( lambda achv: achv.sphere == sphere.value, valid_locations )) for sphere in SPHERE },

    'name_to_id': { location.name: location.id for location in achievements },
    'id_to_name': { location.id: location.name for location in achievements },
}

